name = "client-xxx-event-scan-worker"
main = "src/index.js"
compatibility_date = "2026-01-25"

[[d1_databases]]
binding = "DB"
database_name = "client-xxx-event-scan-db"

migrations_dir = "migrations"
