name = "client-xxx-event-scan-worker"
main = "src/index.js"
compatibility_date = "2026-01-25"

[[d1_databases]]
binding = "DB"
database_name = "client-xxx-event-scan-db"
database_id = "447a2f50-c6fd-460e-8b33-a7ebae8ab4d1"

migrations_dir = "migrations"
